title: Jordan Hutchings # your name (or website title) here
logo: "/images/headshot2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I am a Pre-doctoral Researcher at The Vancouver School of Economics at the University of British Columbia. 
  This website is a place where I can post some of the work I am up to. 
  <br>
  Feel free to have a look around :)
  <br><br>
  <a href="https://www.linkedin.com/in/jordan-hutchings/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
